/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as MoveImport } from './routes/move'
import { Route as LoginImport } from './routes/login'
import { Route as ItemImport } from './routes/item'
import { Route as AbilityImport } from './routes/ability'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonIndexImport } from './routes/pokemon.index'
import { Route as UserProfileImport } from './routes/user/profile'
import { Route as PokemonIdImport } from './routes/pokemon.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const MoveRoute = MoveImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ItemRoute = ItemImport.update({
  id: '/item',
  path: '/item',
  getParentRoute: () => rootRoute,
} as any)

const AbilityRoute = AbilityImport.update({
  id: '/ability',
  path: '/ability',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIndexRoute = PokemonIndexImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRoute,
} as any)

const UserProfileRoute = UserProfileImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIdRoute = PokemonIdImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ability': {
      id: '/ability'
      path: '/ability'
      fullPath: '/ability'
      preLoaderRoute: typeof AbilityImport
      parentRoute: typeof rootRoute
    }
    '/item': {
      id: '/item'
      path: '/item'
      fullPath: '/item'
      preLoaderRoute: typeof ItemImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdImport
      parentRoute: typeof rootRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ability': typeof AbilityRoute
  '/item': typeof ItemRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/profile': typeof UserProfileRoute
  '/pokemon': typeof PokemonIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ability': typeof AbilityRoute
  '/item': typeof ItemRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/profile': typeof UserProfileRoute
  '/pokemon': typeof PokemonIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ability': typeof AbilityRoute
  '/item': typeof ItemRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/signup': typeof SignupRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/user/profile': typeof UserProfileRoute
  '/pokemon/': typeof PokemonIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ability'
    | '/item'
    | '/login'
    | '/move'
    | '/signup'
    | '/pokemon/$id'
    | '/user/profile'
    | '/pokemon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ability'
    | '/item'
    | '/login'
    | '/move'
    | '/signup'
    | '/pokemon/$id'
    | '/user/profile'
    | '/pokemon'
  id:
    | '__root__'
    | '/'
    | '/ability'
    | '/item'
    | '/login'
    | '/move'
    | '/signup'
    | '/pokemon/$id'
    | '/user/profile'
    | '/pokemon/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbilityRoute: typeof AbilityRoute
  ItemRoute: typeof ItemRoute
  LoginRoute: typeof LoginRoute
  MoveRoute: typeof MoveRoute
  SignupRoute: typeof SignupRoute
  PokemonIdRoute: typeof PokemonIdRoute
  UserProfileRoute: typeof UserProfileRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbilityRoute: AbilityRoute,
  ItemRoute: ItemRoute,
  LoginRoute: LoginRoute,
  MoveRoute: MoveRoute,
  SignupRoute: SignupRoute,
  PokemonIdRoute: PokemonIdRoute,
  UserProfileRoute: UserProfileRoute,
  PokemonIndexRoute: PokemonIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ability",
        "/item",
        "/login",
        "/move",
        "/signup",
        "/pokemon/$id",
        "/user/profile",
        "/pokemon/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ability": {
      "filePath": "ability.tsx"
    },
    "/item": {
      "filePath": "item.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/move": {
      "filePath": "move.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/pokemon/$id": {
      "filePath": "pokemon.$id.tsx"
    },
    "/user/profile": {
      "filePath": "user/profile.tsx"
    },
    "/pokemon/": {
      "filePath": "pokemon.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
